### ISSUE TITLE
Is there a docker version of PanVA?

### ISSUE THREAD

**Issue by HuYanhong** [astridvandenbrandt/PanVA#1]
Some npm packages are no longer supported or maintained. So, is there a docker version of PanVA?

**Comment by astridvandenbrandt** [comment]
Hi, 

This repo is not actively maintained anymore. However, we have a new repo with a docker version of PanVA. You can find it [here: https://github.com/PanBrowse/PanVA](https://github.com/PanBrowse/PanVA).

We updated the readme of this current repo such that the new codebase is findable. Thank you for pointing it out to us!
